//! Recovery of the UE3 native registration data from symbol names.
//!
//! UE3 leaves a regular, name-encoded trail for every native package and class:
//!
//! | Symbol shape | Meaning |
//! |---|---|
//! | `AutoInitializeRegistrants<Pkg>(int&)` | package registers its native classes |
//! | `AutoGenerateNames<Pkg>()` | package registers its FNames (script events called from C++) |
//! | `<Class>::PrivateStaticClass` | one per native class (`DECLARE_CLASS`/`IMPLEMENT_CLASS`) |
//! | `G<pkg><Class>Natives` | `FNativeFunctionLookup` table of a class with natives |
//! | `<Class>::exec<Func>(FFrame&, void*)` | script-callable native thunk |
//! | `int<Class>exec<Func>` | `IMPLEMENT_FUNCTION` native pointer (extern "C") |
//! | `<PKG>_<Name>` | FName global generated by `AutoGenerateNames` |
//! | `__GLOBAL__sub_I_<file>` | static initialiser of one compilation unit |
//!
//! The class → module assignment uses the debug map (the unit that defined
//! `PrivateStaticClass`), which is direct evidence; the natives-table package
//! prefix is reported alongside as an independent cross-check.

use std::collections::{BTreeMap, BTreeSet};

use serde::Serialize;

use crate::analysis::Analysis;
use crate::classify::FNAME_PREFIXES;
use crate::demangle::{split_owner, strip_macho_underscore};
use crate::macho::SymKind;
use crate::provenance::Component;

/// Per-class native data.
#[derive(Debug, Clone, Default, Serialize, PartialEq, Eq)]
pub struct ClassInfo {
    /// UE3 source module that defined `PrivateStaticClass` (debug map).
    pub module: Option<String>,
    /// Category of the `PrivateStaticClass` symbol.
    pub category: String,
    /// Package prefix of the `G<pkg><Class>Natives` table, if present.
    pub natives_table_pkg: Option<String>,
    /// Number of `<Class>::exec*(FFrame&, void*)` thunks.
    pub exec_thunks: u32,
    /// Number of `int<Class>exec*` registrations.
    pub int_registrations: u32,
    /// Address of `PrivateStaticClass`.
    pub private_static_class: Option<String>,
}

/// Per-module rollup.
#[derive(Debug, Clone, Default, Serialize, PartialEq, Eq)]
pub struct ModuleNatives {
    /// Native classes (`PrivateStaticClass`) defined by the module.
    pub classes: u32,
    /// Classes with at least one exec thunk.
    pub classes_with_natives: u32,
    /// Sum of exec thunks.
    pub exec_thunks: u32,
    /// Class name → exec-thunk count, for classes with at least one thunk.
    pub class_exec_counts: BTreeMap<String, u32>,
    /// Native classes without exec thunks, listed only when the module has at
    /// most [`MAX_LISTED_CLASSES_WITHOUT_NATIVES`] of them (Engine: count only).
    pub classes_without_natives: Option<Vec<String>>,
}

/// Cap for listing classes without natives per module.
pub const MAX_LISTED_CLASSES_WITHOUT_NATIVES: usize = 150;

/// Registration summary.
#[derive(Debug, Clone, Default, Serialize, PartialEq, Eq)]
pub struct Registry {
    /// Packages with `AutoInitializeRegistrants<Pkg>`.
    pub registrant_packages: BTreeSet<String>,
    /// Packages with `AutoGenerateNames<Pkg>`.
    pub generate_names_packages: BTreeSet<String>,
    /// Package prefixes seen in `G<pkg><Class>Natives` table names → table count.
    pub natives_table_prefixes: BTreeMap<String, u32>,
    /// Total `G…Natives` tables.
    pub natives_tables: u32,
    /// `G…Natives` tables whose class has no `PrivateStaticClass`.
    pub natives_tables_without_class: Vec<String>,
    /// Total native classes (`PrivateStaticClass`).
    pub native_classes: u32,
    /// Total exec thunks.
    pub exec_thunks: u32,
    /// Total `int<Class>exec<Func>` registrations.
    pub int_registrations: u32,
    /// `int…exec…` registrations that could not be matched to a known class.
    pub int_registrations_unmatched: u32,
    /// Classes where exec-thunk and int-registration counts differ.
    pub exec_int_mismatches: BTreeMap<String, (u32, u32)>,
    /// Per-module rollup (UE3 module dir from the debug map; `?` if unknown).
    pub modules: BTreeMap<String, ModuleNatives>,
    /// FName globals by package prefix (`ENGINE_`, ...).
    pub fname_globals: BTreeMap<String, u32>,
    /// `__GLOBAL__sub_I_<file>` initialisers.
    pub static_initializers: u32,
    /// Debug-map compilation units per component id.
    pub units_per_component: BTreeMap<String, u32>,
    /// Compilation-unit file names per UE3 module (debug map, sanitized).
    pub ue3_module_units: BTreeMap<String, Vec<String>>,
    /// Version hints of external libraries (`libvorbis` → `1.3.2`).
    pub external_versions: BTreeMap<String, String>,
    /// SDK marker directories of PhysX / Scaleform (e.g. `PhysX_284_UE3`).
    pub sdk_markers: BTreeSet<String>,
    /// Per-class details (keyed by class name).
    pub classes: BTreeMap<String, ClassInfo>,
}

/// If `qualified` is `<Class>::exec<Func>` and `full` is the canonical thunk
/// signature, return (`Class`, `execFunc`).
pub fn exec_thunk<'a>(qualified: &'a str, full: &str) -> Option<(&'a str, &'a str)> {
    let (owner, leaf) = split_owner(qualified);
    if owner.is_empty()
        || owner.contains("::")
        || owner.contains('(')
        || owner.contains('<')
        || !leaf.starts_with("exec")
        || leaf.len() <= 4
    {
        return None;
    }
    let expected_tail = "(FFrame&, void*)";
    let rest = full.strip_prefix(qualified)?;
    (rest == expected_tail).then_some((owner, leaf))
}

/// Split `G<pkg><Class>Natives` using the known package names (case-insensitive,
/// longest match first). Returns (pkg as written, class).
pub fn split_natives_table<'a>(name: &'a str, packages: &[String]) -> Option<(&'a str, &'a str)> {
    let inner = name.strip_prefix('G')?.strip_suffix("Natives")?;
    if inner.is_empty() {
        return None;
    }
    let mut sorted: Vec<&String> = packages.iter().collect();
    sorted.sort_by_key(|p| std::cmp::Reverse(p.len()));
    for pkg in sorted {
        let n = pkg.len();
        if inner.len() > n
            && inner
                .get(..n)
                .map(|p| p.eq_ignore_ascii_case(pkg))
                .unwrap_or(false)
        {
            let class = inner.get(n..)?;
            let mut c = class.chars();
            if matches!(c.next(), Some('U' | 'A')) && c.next().is_some() {
                return Some((inner.get(..n)?, class));
            }
        }
    }
    None
}

/// Build the registry from an analysis.
pub fn build(a: &Analysis) -> Registry {
    let mut reg = Registry::default();

    // Pass 1: packages, classes, FNames, initialisers.
    for e in &a.entries {
        let Some(sym) = a.symbol(e) else { continue };
        let name = strip_macho_underscore(&sym.raw);
        let q = a.qualified(e);
        if sym.kind == SymKind::Text {
            if let Some(pkg) = q.strip_prefix("AutoInitializeRegistrants")
                && !pkg.is_empty()
            {
                reg.registrant_packages.insert(pkg.to_string());
            }
            if let Some(pkg) = q.strip_prefix("AutoGenerateNames")
                && !pkg.is_empty()
            {
                reg.generate_names_packages.insert(pkg.to_string());
            }
            if name.starts_with("_GLOBAL__sub_I_") {
                reg.static_initializers = reg.static_initializers.saturating_add(1);
            }
        }
        if sym.kind != SymKind::Undefined
            && sym.kind != SymKind::Text
            && let Some(class) = q.strip_suffix("::PrivateStaticClass")
            && !class.contains("::")
        {
            let info = reg.classes.entry(class.to_string()).or_default();
            info.module = a.module(e).map(str::to_string);
            info.category = e.category.id().to_string();
            info.private_static_class = Some(format!("0x{:x}", sym.value));
        }
        if sym.kind != SymKind::Undefined && e.full.is_none() {
            for p in FNAME_PREFIXES {
                if name.starts_with(p) && name.len() > p.len() {
                    let c = reg.fname_globals.entry(p.to_string()).or_insert(0);
                    *c = c.saturating_add(1);
                }
            }
        }
    }
    reg.native_classes = u32::try_from(reg.classes.len()).unwrap_or(u32::MAX);

    // Package names used to split natives tables: registrant packages plus
    // UE3 module directory names.
    let mut packages: Vec<String> = reg
        .registrant_packages
        .iter()
        .chain(reg.generate_names_packages.iter())
        .cloned()
        .collect();
    for u in &a.image.units {
        if let Component::Ue3Module(m) = &u.component {
            packages.push(m.clone());
        }
    }
    packages.sort();
    packages.dedup();

    // Pass 2: exec thunks, int registrations, natives tables.
    let class_names: Vec<String> = reg.classes.keys().cloned().collect();
    for e in &a.entries {
        let Some(sym) = a.symbol(e) else { continue };
        let name = strip_macho_underscore(&sym.raw);
        if sym.kind == SymKind::Text
            && let (Some(q), Some(full)) = (e.qualified.as_deref(), e.full.as_deref())
            && let Some((owner, _leaf)) = exec_thunk(q, full)
        {
            reg.exec_thunks = reg.exec_thunks.saturating_add(1);
            let info = reg.classes.entry(owner.to_string()).or_default();
            info.exec_thunks = info.exec_thunks.saturating_add(1);
            continue;
        }
        if sym.kind == SymKind::Undefined || e.full.is_some() {
            continue;
        }
        if let Some(rest) = name.strip_prefix("int")
            && rest.contains("exec")
            && (rest.starts_with('U') || rest.starts_with('A'))
        {
            reg.int_registrations = reg.int_registrations.saturating_add(1);
            // Longest class name C such that rest starts with C + "exec".
            let mut best: Option<&String> = None;
            for c in &class_names {
                if rest.len() > c.len()
                    && rest.starts_with(c.as_str())
                    && rest.get(c.len()..).map(|t| t.starts_with("exec")) == Some(true)
                    && best.map(|b| c.len() > b.len()).unwrap_or(true)
                {
                    best = Some(c);
                }
            }
            match best.and_then(|c| reg.classes.get_mut(c)) {
                Some(info) => info.int_registrations = info.int_registrations.saturating_add(1),
                None => {
                    reg.int_registrations_unmatched =
                        reg.int_registrations_unmatched.saturating_add(1)
                }
            }
            continue;
        }
        if name.starts_with('G')
            && name.ends_with("Natives")
            && let Some((pkg, class)) = split_natives_table(name, &packages)
        {
            reg.natives_tables = reg.natives_tables.saturating_add(1);
            let c = reg
                .natives_table_prefixes
                .entry(pkg.to_string())
                .or_insert(0);
            *c = c.saturating_add(1);
            match reg.classes.get_mut(class) {
                Some(info) => info.natives_table_pkg = Some(pkg.to_string()),
                None => reg.natives_tables_without_class.push(class.to_string()),
            }
        }
    }
    reg.natives_tables_without_class.sort();

    // Classes that only appeared through exec thunks (no PrivateStaticClass)
    // keep `module = None`; count them separately via the "?" module.
    for (name, info) in &reg.classes {
        if info.exec_thunks != info.int_registrations {
            reg.exec_int_mismatches
                .insert(name.clone(), (info.exec_thunks, info.int_registrations));
        }
        let module = info.module.clone().unwrap_or_else(|| "?".to_string());
        let m = reg.modules.entry(module).or_insert_with(|| ModuleNatives {
            classes_without_natives: Some(Vec::new()),
            ..ModuleNatives::default()
        });
        if info.private_static_class.is_some() {
            m.classes = m.classes.saturating_add(1);
        }
        if info.exec_thunks > 0 {
            m.classes_with_natives = m.classes_with_natives.saturating_add(1);
        }
        m.exec_thunks = m.exec_thunks.saturating_add(info.exec_thunks);
        if info.exec_thunks > 0 {
            m.class_exec_counts.insert(name.clone(), info.exec_thunks);
        } else {
            m.classes_without_natives
                .get_or_insert_with(Vec::new)
                .push(name.clone());
        }
    }
    for m in reg.modules.values_mut() {
        if m.classes_without_natives
            .as_ref()
            .is_some_and(|v| v.len() > MAX_LISTED_CLASSES_WITHOUT_NATIVES)
        {
            m.classes_without_natives = None;
        }
    }

    // Compilation units.
    for u in &a.image.units {
        let c = reg.units_per_component.entry(u.component.id()).or_insert(0);
        *c = c.saturating_add(1);
        if let Component::Ue3Module(m) = &u.component {
            let file = u.rel_path.rsplit('/').next().unwrap_or("").to_string();
            reg.ue3_module_units
                .entry(m.clone())
                .or_default()
                .push(file);
        }
        if let (Component::External(lib), Some(v)) = (&u.component, &u.version_hint) {
            reg.external_versions.insert(lib.clone(), v.clone());
        }
        if let Some(marker) = &u.sdk_marker {
            reg.sdk_markers.insert(marker.clone());
        }
    }
    for files in reg.ue3_module_units.values_mut() {
        files.sort();
        files.dedup();
    }
    reg
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exec_thunk_shapes() {
        assert_eq!(
            exec_thunk(
                "APawn::execSetPhysics",
                "APawn::execSetPhysics(FFrame&, void*)"
            ),
            Some(("APawn", "execSetPhysics"))
        );
        // Wrong signature.
        assert_eq!(exec_thunk("APawn::execFoo", "APawn::execFoo(int)"), None);
        // Nested local class inside an exec thunk.
        assert_eq!(
            exec_thunk(
                "ULightComponent::execX(FFrame&, void*)::Cmd::Execute",
                "ULightComponent::execX(FFrame&, void*)::Cmd::Execute()"
            ),
            None
        );
        // PhysX `execute` is not a thunk.
        assert_eq!(
            exec_thunk("SceneQuery::execute", "SceneQuery::execute()"),
            None
        );
        assert_eq!(exec_thunk("A::exec", "A::exec(FFrame&, void*)"), None);
        assert_eq!(exec_thunk("", ""), None);
    }

    #[test]
    fn natives_table_split_is_case_insensitive() {
        let pkgs = vec![
            "ASAMU".to_string(),
            "Engine".to_string(),
            "GameFramework".to_string(),
            "Core".to_string(),
        ];
        assert_eq!(
            split_natives_table("GasamuUASAMUSystemSettingsManagerNatives", &pkgs),
            Some(("asamu", "UASAMUSystemSettingsManager"))
        );
        assert_eq!(
            split_natives_table("GEngineAActorNatives", &pkgs),
            Some(("Engine", "AActor"))
        );
        assert_eq!(split_natives_table("GNatives", &pkgs), None);
        assert_eq!(split_natives_table("GEngineNatives", &pkgs), None);
        assert_eq!(split_natives_table("GFooUBarNatives", &pkgs), None);
        assert_eq!(split_natives_table("Natives", &pkgs), None);
    }
}
