//! Markdown summary of comparisons, for `docs/PARITY.md`.
//!
//! Input: comparison summaries ([`crate::compare::CompareSummary`], written by
//! `asamu-trace compare --json`). Output: one table row per comparison
//! (errors of the trace under test against the reference) plus the
//! tolerances and the first divergences. The text says where the numbers
//! come from so it can be pasted into the "measured" columns as it is.
//!
//! Rows are aligned by tick index. The last column says how the two traces
//! stepped (a fixed rate, or the range of a variable-rate trace's frame
//! lengths); a comparison whose traces stepped the same ticks with different
//! frame lengths is marked there and listed under the table, because its
//! errors include the step difference
//! ([`crate::compare::TimingSummary`]).

use std::fmt::Write as _;

use crate::compare::{CompareSummary, Verdict, describe_steps};

fn verdict(v: Verdict) -> &'static str {
    match v {
        Verdict::Exact => "exact",
        Verdict::WithinTolerance => "within tolerance",
        Verdict::Diverged => "diverged",
        Verdict::NoOverlap => "no common ticks",
    }
}

fn cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

/// The "Time step" cell: how both traces stepped; `?` for a summary written
/// before the timing check existed.
fn steps(s: &CompareSummary) -> String {
    let Some(t) = &s.timing else {
        return "?".to_owned();
    };
    let (a, b) = (describe_steps(&s.a, &t.a), describe_steps(&s.b, &t.b));
    if !t.aligned() {
        format!("**differs**: a {a}, b {b}")
    } else if a == b {
        a
    } else {
        format!("a {a}, b {b}")
    }
}

/// Renders the markdown report.
#[must_use]
pub fn render_markdown(title: &str, summaries: &[(String, CompareSummary)]) -> String {
    let mut o = String::new();
    let _ = writeln!(o, "### {}", cell(title));
    let _ = writeln!(o);
    let _ = writeln!(
        o,
        "Generated by `asamu-trace report` from {} comparison(s) (`asamu-trace compare --json`). \
         Reference (a) = recorded trace, tested (b) = our replay unless stated otherwise. \
         Angles in degrees, distances in UU, speeds in UU/s; max / RMS over matched ticks \
         (traces are aligned by tick index).",
        summaries.len()
    );
    let _ = writeln!(o);
    let _ = writeln!(
        o,
        "| Comparison | Level | a → b | Ticks | Position max / RMS | Velocity max / RMS | Yaw max | Pitch max | Grounded / grapple mismatches | First divergence | Verdict | Time step |"
    );
    let _ = writeln!(o, "|---|---|---|---:|---|---|---:|---:|---|---|---|---|");
    for (name, s) in summaries {
        let d = &s.diff;
        let first = d.first_divergence.map_or_else(
            || "none".to_owned(),
            |f| {
                format!(
                    "tick {} ({}, {:.4})",
                    f.tick,
                    serde_json::to_value(f.field)
                        .ok()
                        .and_then(|v| v.as_str().map(str::to_owned))
                        .unwrap_or_default(),
                    f.error
                )
            },
        );
        let level = s.a.level.as_deref().or(s.b.level.as_deref()).unwrap_or("?");
        let _ = writeln!(
            o,
            "| {} | {} | {:?} → {:?} | {} | {:.3} / {:.3} | {:.3} / {:.3} | {:.4} | {:.4} | {} / {} | {} | {} | {} |",
            cell(name),
            cell(level),
            s.a.source,
            s.b.source,
            d.matched,
            d.position.max,
            d.position.rms,
            d.velocity.max,
            d.velocity.rms,
            d.yaw.max.to_degrees(),
            d.pitch.max.to_degrees(),
            d.grounded_mismatches,
            d.grapple_state_mismatches,
            cell(&first),
            verdict(s.verdict),
            cell(&steps(s))
        );
    }
    let _ = writeln!(o);
    // Each distinct tolerance set once, in first-seen order.
    let mut tolerances: Vec<String> = Vec::new();
    for (_, s) in summaries {
        let t = &s.tolerances;
        let line = format!(
            "position {} uu, velocity {} uu/s, angle {} rad, fov {} deg, anchor {} uu",
            t.position, t.velocity, t.angle, t.fov, t.anchor
        );
        if !tolerances.contains(&line) {
            tolerances.push(line);
        }
    }
    for t in tolerances {
        let _ = writeln!(o, "Tolerances: {t}.");
    }
    let unmatched: Vec<String> = summaries
        .iter()
        .filter(|(_, s)| s.diff.only_in_a > 0 || s.diff.only_in_b > 0)
        .map(|(n, s)| {
            format!(
                "{} ({} only in a, {} only in b)",
                cell(n),
                s.diff.only_in_a,
                s.diff.only_in_b
            )
        })
        .collect();
    if !unmatched.is_empty() {
        let _ = writeln!(o);
        let _ = writeln!(o, "Unmatched ticks: {}.", unmatched.join("; "));
    }
    let misstepped: Vec<String> = summaries
        .iter()
        .filter_map(|(n, s)| {
            let t = s.timing.as_ref().filter(|t| !t.aligned())?;
            let first = t
                .first_mismatch
                .map_or_else(String::new, |m| format!(", first at tick {}", m.tick));
            Some(format!(
                "{} ({} of {} ticks{first}; elapsed time differs by up to {:.3} s)",
                cell(n),
                t.mismatches,
                t.compared,
                t.max_time_skew
            ))
        })
        .collect();
    if !misstepped.is_empty() {
        let _ = writeln!(o);
        let _ = writeln!(
            o,
            "Frame lengths differ between the two traces, so these errors include the step \
             difference: {}.",
            misstepped.join("; ")
        );
    }
    o
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compare::compare_traces;
    use asamu_core::glam::Vec3;
    use asamu_player::trace::{CompareTolerances, TraceGrappleState};
    use asamu_player::{InputFrame, Trace, TraceMeta, TraceSample};

    fn trace(n: u64, dx: f32) -> Trace {
        Trace {
            meta: TraceMeta::runtime(Some("AG-Workshop".into()), Some(60.0)),
            samples: (0..n)
                .map(|tick| TraceSample {
                    tick,
                    time: 0.0,
                    input: InputFrame::default(),
                    position: Vec3::new(tick as f32 * dx, 0.0, 0.0),
                    velocity: Vec3::ZERO,
                    yaw: 0.0,
                    pitch: 0.0,
                    fov: 90.0,
                    grapple_state: TraceGrappleState::Idle,
                    grapple_anchor: None,
                    rope_length: None,
                    grounded: true,
                })
                .collect(),
        }
    }

    #[test]
    fn markdown_rows() {
        let a = trace(5, 1.0);
        let b = trace(6, 1.5);
        let tol = CompareTolerances {
            position: 1.0,
            ..CompareTolerances::default()
        };
        let s1 = compare_traces("a", &a, "b", &b, &tol);
        let s2 = compare_traces("a", &a, "a", &a, &tol);
        let md = render_markdown(
            "Walk | forward",
            &[("walk-1".into(), s1), ("self".into(), s2)],
        );
        assert!(md.starts_with("### Walk \\| forward\n"), "{md}");
        assert!(
            md.contains("| walk-1 | AG-Workshop | Runtime → Runtime | 5 | 2.000 / "),
            "{md}"
        );
        assert!(md.contains("tick 3 (position, 1.5000)"), "{md}");
        assert!(md.contains("| self | AG-Workshop |"), "{md}");
        assert!(md.contains("| exact |"), "{md}");
        assert!(md.contains("Tolerances: position 1 uu"), "{md}");
        assert!(md.contains("walk-1 (0 only in a, 1 only in b)"), "{md}");

        // Distinct tolerance sets are listed once each, in first-seen order.
        let loose = CompareTolerances {
            position: 2.0,
            ..CompareTolerances::default()
        };
        let s3 = compare_traces("a", &a, "b", &b, &loose);
        let s1 = compare_traces("a", &a, "b", &b, &tol);
        let s2 = compare_traces("a", &a, "a", &a, &tol);
        let md = render_markdown(
            "t",
            &[
                ("1".into(), s1.clone()),
                ("3".into(), s3),
                ("2".into(), s2),
                ("1b".into(), s1),
            ],
        );
        let lines: Vec<&str> = md
            .lines()
            .filter(|l| l.starts_with("Tolerances:"))
            .collect();
        assert_eq!(lines.len(), 2, "{md}");
        assert!(lines[0].starts_with("Tolerances: position 1 uu"), "{md}");
        assert!(lines[1].starts_with("Tolerances: position 2 uu"), "{md}");
        // Fixed-rate comparisons with matching steps add nothing below the
        // table.
        assert!(!md.contains("Frame lengths differ"), "{md}");
    }

    /// `trace(n, 1.0)` with real sample times: fixed 60 Hz, or the given
    /// frame lengths and no fixed rate.
    fn timed(n: u64, lengths: Option<&dyn Fn(u64) -> f64>) -> Trace {
        let mut t = trace(n, 1.0);
        let mut time = 0.0;
        for s in &mut t.samples {
            if s.tick > 0 {
                time += lengths.map_or(1.0 / 60.0, |f| f(s.tick));
            }
            s.time = time;
        }
        if lengths.is_some() {
            t.meta.tick_rate = None;
        }
        t
    }

    #[test]
    fn time_step_column() {
        let tol = CompareTolerances::default();
        let fixed = timed(40, None);
        let uneven = |k: u64| 0.014 + 0.001 * (k % 5) as f64;
        let var = timed(40, Some(&uneven));
        let same = compare_traces("a", &fixed, "b", &fixed, &tol);
        let per_sample = compare_traces("a", &var, "b", &var, &tol);
        let misstepped = compare_traces("a", &var, "b", &fixed, &tol);
        let mut forced = var.clone();
        forced.meta.tick_rate = Some(60.0);
        let labels = compare_traces("a", &var, "b", &forced, &tol);
        let mut old = same.clone();
        old.timing = None;
        let md = render_markdown(
            "t",
            &[
                ("fixed".into(), same),
                ("variable".into(), per_sample),
                ("wrong-step".into(), misstepped),
                ("labels".into(), labels),
                ("old".into(), old),
            ],
        );
        let row = |name: &str| {
            md.lines()
                .find(|l| l.starts_with(&format!("| {name} |")))
                .unwrap_or_else(|| panic!("no row {name}:\n{md}"))
                .to_owned()
        };
        assert!(md.contains("| Verdict | Time step |"), "{md}");
        assert!(row("fixed").ends_with("| exact | 60 Hz |"), "{md}");
        assert!(
            row("variable")
                .ends_with("| exact | variable 0.014000..0.018000 s (mean 0.016051 s) |"),
            "{md}"
        );
        assert!(
            row("wrong-step").ends_with(
                "| exact | **differs**: a variable 0.014000..0.018000 s (mean 0.016051 s), b 60 Hz |"
            ),
            "{md}"
        );
        // Same lengths under different labels: both are named.
        assert!(
            row("labels")
                .ends_with("| a variable 0.014000..0.018000 s (mean 0.016051 s), b 60 Hz |"),
            "{md}"
        );
        assert!(!row("labels").contains("differs"), "{md}");
        assert!(row("old").ends_with("| exact | ? |"), "{md}");
        let notes: Vec<&str> = md
            .lines()
            .filter(|l| l.starts_with("Frame lengths differ"))
            .collect();
        assert_eq!(notes.len(), 1, "{md}");
        assert!(
            notes[0].contains(
                "wrong-step (39 of 39 ticks, first at tick 1; elapsed time differs by up to 0.0"
            ),
            "{md}"
        );
        assert!(!notes[0].contains("labels") && !notes[0].contains("variable ("));
        // Every table row has the same number of cells as the header.
        let cells = |l: &str| l.matches(" | ").count();
        let header = md.lines().find(|l| l.starts_with("| Comparison")).unwrap();
        for name in ["fixed", "variable", "wrong-step", "labels", "old"] {
            assert_eq!(cells(&row(name)), cells(header), "{name}\n{md}");
        }
    }
}
