//! Markdown summary of comparisons, for `docs/PARITY.md`.
//!
//! Input: comparison summaries ([`crate::compare::CompareSummary`], written by
//! `asamu-trace compare --json`). Output: one table row per comparison
//! (errors of the trace under test against the reference) plus the
//! tolerances and the first divergences. The text says where the numbers
//! come from so it can be pasted into the "measured" columns as it is.

use std::fmt::Write as _;

use crate::compare::{CompareSummary, Verdict};

fn verdict(v: Verdict) -> &'static str {
    match v {
        Verdict::Exact => "exact",
        Verdict::WithinTolerance => "within tolerance",
        Verdict::Diverged => "diverged",
        Verdict::NoOverlap => "no common ticks",
    }
}

fn cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

/// Renders the markdown report.
#[must_use]
pub fn render_markdown(title: &str, summaries: &[(String, CompareSummary)]) -> String {
    let mut o = String::new();
    let _ = writeln!(o, "### {}", cell(title));
    let _ = writeln!(o);
    let _ = writeln!(
        o,
        "Generated by `asamu-trace report` from {} comparison(s) (`asamu-trace compare --json`). \
         Reference (a) = recorded trace, tested (b) = our replay unless stated otherwise. \
         Angles in degrees, distances in UU, speeds in UU/s; max / RMS over matched ticks.",
        summaries.len()
    );
    let _ = writeln!(o);
    let _ = writeln!(
        o,
        "| Comparison | Level | a → b | Ticks | Position max / RMS | Velocity max / RMS | Yaw max | Pitch max | Grounded / grapple mismatches | First divergence | Verdict |"
    );
    let _ = writeln!(o, "|---|---|---|---:|---|---|---:|---:|---|---|---|");
    for (name, s) in summaries {
        let d = &s.diff;
        let first = d.first_divergence.map_or_else(
            || "none".to_owned(),
            |f| {
                format!(
                    "tick {} ({}, {:.4})",
                    f.tick,
                    serde_json::to_value(f.field)
                        .ok()
                        .and_then(|v| v.as_str().map(str::to_owned))
                        .unwrap_or_default(),
                    f.error
                )
            },
        );
        let level = s.a.level.as_deref().or(s.b.level.as_deref()).unwrap_or("?");
        let _ = writeln!(
            o,
            "| {} | {} | {:?} → {:?} | {} | {:.3} / {:.3} | {:.3} / {:.3} | {:.4} | {:.4} | {} / {} | {} | {} |",
            cell(name),
            cell(level),
            s.a.source,
            s.b.source,
            d.matched,
            d.position.max,
            d.position.rms,
            d.velocity.max,
            d.velocity.rms,
            d.yaw.max.to_degrees(),
            d.pitch.max.to_degrees(),
            d.grounded_mismatches,
            d.grapple_state_mismatches,
            cell(&first),
            verdict(s.verdict)
        );
    }
    let _ = writeln!(o);
    // Each distinct tolerance set once, in first-seen order.
    let mut tolerances: Vec<String> = Vec::new();
    for (_, s) in summaries {
        let t = &s.tolerances;
        let line = format!(
            "position {} uu, velocity {} uu/s, angle {} rad, fov {} deg, anchor {} uu",
            t.position, t.velocity, t.angle, t.fov, t.anchor
        );
        if !tolerances.contains(&line) {
            tolerances.push(line);
        }
    }
    for t in tolerances {
        let _ = writeln!(o, "Tolerances: {t}.");
    }
    let unmatched: Vec<String> = summaries
        .iter()
        .filter(|(_, s)| s.diff.only_in_a > 0 || s.diff.only_in_b > 0)
        .map(|(n, s)| {
            format!(
                "{} ({} only in a, {} only in b)",
                cell(n),
                s.diff.only_in_a,
                s.diff.only_in_b
            )
        })
        .collect();
    if !unmatched.is_empty() {
        let _ = writeln!(o);
        let _ = writeln!(o, "Unmatched ticks: {}.", unmatched.join("; "));
    }
    o
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compare::compare_traces;
    use asamu_core::glam::Vec3;
    use asamu_player::trace::{CompareTolerances, TraceGrappleState};
    use asamu_player::{InputFrame, Trace, TraceMeta, TraceSample};

    fn trace(n: u64, dx: f32) -> Trace {
        Trace {
            meta: TraceMeta::runtime(Some("AG-Workshop".into()), Some(60.0)),
            samples: (0..n)
                .map(|tick| TraceSample {
                    tick,
                    time: 0.0,
                    input: InputFrame::default(),
                    position: Vec3::new(tick as f32 * dx, 0.0, 0.0),
                    velocity: Vec3::ZERO,
                    yaw: 0.0,
                    pitch: 0.0,
                    fov: 90.0,
                    grapple_state: TraceGrappleState::Idle,
                    grapple_anchor: None,
                    rope_length: None,
                    grounded: true,
                })
                .collect(),
        }
    }

    #[test]
    fn markdown_rows() {
        let a = trace(5, 1.0);
        let b = trace(6, 1.5);
        let tol = CompareTolerances {
            position: 1.0,
            ..CompareTolerances::default()
        };
        let s1 = compare_traces("a", &a, "b", &b, &tol);
        let s2 = compare_traces("a", &a, "a", &a, &tol);
        let md = render_markdown(
            "Walk | forward",
            &[("walk-1".into(), s1), ("self".into(), s2)],
        );
        assert!(md.starts_with("### Walk \\| forward\n"), "{md}");
        assert!(
            md.contains("| walk-1 | AG-Workshop | Runtime → Runtime | 5 | 2.000 / "),
            "{md}"
        );
        assert!(md.contains("tick 3 (position, 1.5000)"), "{md}");
        assert!(md.contains("| self | AG-Workshop |"), "{md}");
        assert!(md.contains("| exact |"), "{md}");
        assert!(md.contains("Tolerances: position 1 uu"), "{md}");
        assert!(md.contains("walk-1 (0 only in a, 1 only in b)"), "{md}");

        // Distinct tolerance sets are listed once each, in first-seen order.
        let loose = CompareTolerances {
            position: 2.0,
            ..CompareTolerances::default()
        };
        let s3 = compare_traces("a", &a, "b", &b, &loose);
        let s1 = compare_traces("a", &a, "b", &b, &tol);
        let s2 = compare_traces("a", &a, "a", &a, &tol);
        let md = render_markdown(
            "t",
            &[
                ("1".into(), s1.clone()),
                ("3".into(), s3),
                ("2".into(), s2),
                ("1b".into(), s1),
            ],
        );
        let lines: Vec<&str> = md
            .lines()
            .filter(|l| l.starts_with("Tolerances:"))
            .collect();
        assert_eq!(lines.len(), 2, "{md}");
        assert!(lines[0].starts_with("Tolerances: position 1 uu"), "{md}");
        assert!(lines[1].starts_with("Tolerances: position 2 uu"), "{md}");
    }
}
