//! Markdown summary of comparisons, for `docs/PARITY.md`.
//!
//! Input: comparison summaries ([`crate::compare::CompareSummary`], written by
//! `asamu-trace compare --json`). Output: one table row per comparison
//! (errors of the trace under test against the reference) plus the
//! tolerances and the first divergences. The text says where the numbers
//! come from so it can be pasted into the "measured" columns as it is.
//!
//! Rows are aligned by tick index. The last column says how the two traces
//! stepped (a fixed rate, or the range of a variable-rate trace's frame
//! lengths); a comparison whose traces stepped the same ticks with different
//! frame lengths is marked there and listed under the table, because its
//! errors include the step difference
//! ([`crate::compare::TimingSummary`]).
//!
//! The position and the velocity error are given horizontally and
//! vertically ([`crate::compare::Components`]; a summary written before
//! they existed shows its 3-D number with a `3-D` mark), the angles in
//! degrees and in rotator units. The "Mode" column separates free-running
//! replays (errors accumulate from the start tick) from one-step replays
//! (every tick restarts from the reference: errors of one tick), which must
//! never share a tolerance. Under the table: where the FOV did not count for
//! the verdict and why, and what each replay noted about itself (the end of
//! its validity, what a one-step replay resynchronised, warnings).

use std::fmt::Write as _;

use crate::compare::{AxisStats, CompareSummary, Verdict, describe_steps, radians_to_units};

fn verdict(v: Verdict) -> &'static str {
    match v {
        Verdict::Exact => "exact",
        Verdict::WithinTolerance => "within tolerance",
        Verdict::Diverged => "diverged",
        Verdict::NoOverlap => "no common ticks",
    }
}

fn cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

/// The "Time step" cell: how both traces stepped; `?` for a summary written
/// before the timing check existed.
fn steps(s: &CompareSummary) -> String {
    let Some(t) = &s.timing else {
        return "?".to_owned();
    };
    let (a, b) = (describe_steps(&s.a, &t.a), describe_steps(&s.b, &t.b));
    if !t.aligned() {
        format!("**differs**: a {a}, b {b}")
    } else if a == b {
        a
    } else {
        format!("a {a}, b {b}")
    }
}

/// `max / RMS` of one component.
fn max_rms(a: &AxisStats) -> String {
    format!("{:.3} / {:.3}", a.max, a.rms)
}

/// The vertical cell: `max / RMS` and the range of the signed difference.
fn vertical(a: &AxisStats) -> String {
    match (a.signed_min, a.signed_max) {
        (Some(lo), Some(hi)) => format!("{} ({lo:+.3} .. {hi:+.3})", max_rms(a)),
        _ => max_rms(a),
    }
}

/// An angle cell: degrees and rotator units.
fn angle(max_radians: f64) -> String {
    format!(
        "{:.4}° / {:.1}",
        max_radians.to_degrees(),
        radians_to_units(max_radians)
    )
}

/// Renders the markdown report.
#[must_use]
pub fn render_markdown(title: &str, summaries: &[(String, CompareSummary)]) -> String {
    let mut o = String::new();
    let _ = writeln!(o, "### {}", cell(title));
    let _ = writeln!(o);
    let _ = writeln!(
        o,
        "Generated by `asamu-trace report` from {} comparison(s) (`asamu-trace compare --json`). \
         Reference (a) = recorded trace, tested (b) = our replay unless stated otherwise. \
         Distances in UU, speeds in UU/s; max / RMS over matched ticks (traces are aligned by \
         tick index); the vertical cells add the range of the signed difference b − a; angles as \
         degrees / rotator units (65536 per turn). Mode: free = the replay runs on from its \
         start tick, one-step = every tick restarts from the reference trace's previous sample \
         (errors of one tick, not comparable with free-running ones).",
        summaries.len()
    );
    let _ = writeln!(o);
    let _ = writeln!(
        o,
        "| Comparison | Level | a → b | Mode | Ticks | Position horizontal max / RMS | Position vertical max / RMS (b − a) | Velocity horizontal max / RMS | Velocity vertical max / RMS (b − a) | Yaw max | Pitch max | Grounded / grapple mismatches | First divergence | Verdict | Time step |"
    );
    let _ = writeln!(
        o,
        "|---|---|---|---|---:|---|---|---|---|---:|---:|---|---|---|---|"
    );
    for (name, s) in summaries {
        let d = &s.diff;
        let first = s.deciding_divergence().map_or_else(
            || "none".to_owned(),
            |f| {
                format!(
                    "tick {} ({}, {:.4})",
                    f.tick,
                    serde_json::to_value(f.field)
                        .ok()
                        .and_then(|v| v.as_str().map(str::to_owned))
                        .unwrap_or_default(),
                    f.error
                )
            },
        );
        let level = s.a.level.as_deref().or(s.b.level.as_deref()).unwrap_or("?");
        // A summary without components has the 3-D numbers only.
        let (pos_h, pos_v, vel_h, vel_v) = match &s.components {
            Some(c) => (
                max_rms(&c.position_horizontal),
                vertical(&c.position_vertical),
                max_rms(&c.velocity_horizontal),
                vertical(&c.velocity_vertical),
            ),
            None => (
                format!("3-D: {:.3} / {:.3}", d.position.max, d.position.rms),
                "?".to_owned(),
                format!("3-D: {:.3} / {:.3}", d.velocity.max, d.velocity.rms),
                "?".to_owned(),
            ),
        };
        let _ = writeln!(
            o,
            "| {} | {} | {:?} → {:?} | {} | {} | {} | {} | {} | {} | {} | {} | {} / {} | {} | {} | {} |",
            cell(name),
            cell(level),
            s.a.source,
            s.b.source,
            if s.one_step { "one-step" } else { "free" },
            d.matched,
            pos_h,
            cell(&pos_v),
            vel_h,
            cell(&vel_v),
            angle(d.yaw.max),
            angle(d.pitch.max),
            d.grounded_mismatches,
            d.grapple_state_mismatches,
            cell(&first),
            verdict(s.verdict),
            cell(&steps(s))
        );
    }
    let _ = writeln!(o);
    // Each distinct tolerance set once, in first-seen order.
    let mut tolerances: Vec<String> = Vec::new();
    for (_, s) in summaries {
        let t = &s.tolerances;
        let line = format!(
            "position {} uu, velocity {} uu/s, angle {} rad, fov {} deg, anchor {} uu",
            t.position, t.velocity, t.angle, t.fov, t.anchor
        );
        if !tolerances.contains(&line) {
            tolerances.push(line);
        }
    }
    for t in tolerances {
        let _ = writeln!(o, "Tolerances: {t}.");
    }
    let unmatched: Vec<String> = summaries
        .iter()
        .filter(|(_, s)| s.diff.only_in_a > 0 || s.diff.only_in_b > 0)
        .map(|(n, s)| {
            format!(
                "{} ({} only in a, {} only in b)",
                cell(n),
                s.diff.only_in_a,
                s.diff.only_in_b
            )
        })
        .collect();
    if !unmatched.is_empty() {
        let _ = writeln!(o);
        let _ = writeln!(o, "Unmatched ticks: {}.", unmatched.join("; "));
    }
    let misstepped: Vec<String> = summaries
        .iter()
        .filter_map(|(n, s)| {
            let t = s.timing.as_ref().filter(|t| !t.aligned())?;
            let first = t
                .first_mismatch
                .map_or_else(String::new, |m| format!(", first at tick {}", m.tick));
            Some(format!(
                "{} ({} of {} ticks{first}; elapsed time differs by up to {:.3} s)",
                cell(n),
                t.mismatches,
                t.compared,
                t.max_time_skew
            ))
        })
        .collect();
    if !misstepped.is_empty() {
        let _ = writeln!(o);
        let _ = writeln!(
            o,
            "Frame lengths differ between the two traces, so these errors include the step \
             difference: {}.",
            misstepped.join("; ")
        );
    }
    let fov_out: Vec<String> = summaries
        .iter()
        .filter_map(|(n, s)| {
            let f = s.fov.as_ref().filter(|f| !f.counted)?;
            Some(format!(
                "{} ({}; FOV max {:.3}°)",
                cell(n),
                cell(&f.reason),
                s.diff.fov.max
            ))
        })
        .collect();
    if !fov_out.is_empty() {
        let _ = writeln!(o);
        let _ = writeln!(
            o,
            "The FOV did not count for the verdict of: {}.",
            fov_out.join("; ")
        );
    }
    let noted: Vec<&(String, CompareSummary)> = summaries
        .iter()
        .filter(|(_, s)| !s.harness_notes.is_empty())
        .collect();
    if !noted.is_empty() {
        let _ = writeln!(o);
        let _ = writeln!(o, "What the replays noted about themselves:");
        let _ = writeln!(o);
        for (n, s) in noted {
            for note in &s.harness_notes {
                let _ = writeln!(o, "- {}: {}", cell(n), cell(note));
            }
        }
    }
    o
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compare::compare_traces;
    use asamu_core::glam::Vec3;
    use asamu_player::trace::{CompareTolerances, TraceGrappleState};
    use asamu_player::{InputFrame, Trace, TraceMeta, TraceSample};

    fn trace(n: u64, dx: f32) -> Trace {
        Trace {
            meta: TraceMeta::runtime(Some("AG-Workshop".into()), Some(60.0)),
            samples: (0..n)
                .map(|tick| TraceSample {
                    tick,
                    time: 0.0,
                    input: InputFrame::default(),
                    position: Vec3::new(tick as f32 * dx, 0.0, 0.0),
                    velocity: Vec3::ZERO,
                    yaw: 0.0,
                    pitch: 0.0,
                    fov: 90.0,
                    grapple_state: TraceGrappleState::Idle,
                    grapple_anchor: None,
                    rope_length: None,
                    grounded: true,
                })
                .collect(),
        }
    }

    #[test]
    fn markdown_rows() {
        let a = trace(5, 1.0);
        let b = trace(6, 1.5);
        let tol = CompareTolerances {
            position: 1.0,
            ..CompareTolerances::default()
        };
        let s1 = compare_traces("a", &a, "b", &b, &tol);
        let s2 = compare_traces("a", &a, "a", &a, &tol);
        let md = render_markdown(
            "Walk | forward",
            &[("walk-1".into(), s1), ("self".into(), s2)],
        );
        assert!(md.starts_with("### Walk \\| forward\n"), "{md}");
        assert!(
            md.contains("| walk-1 | AG-Workshop | Runtime → Runtime | free | 5 | 2.000 / "),
            "{md}"
        );
        // Sideways only: the vertical cells are zero, with a zero range.
        assert!(
            md.contains("| 0.000 / 0.000 (+0.000 .. +0.000) | 0.000 / 0.000 | "),
            "{md}"
        );
        assert!(md.contains("tick 3 (position, 1.5000)"), "{md}");
        assert!(md.contains("| self | AG-Workshop |"), "{md}");
        assert!(md.contains("| exact |"), "{md}");
        assert!(md.contains("Tolerances: position 1 uu"), "{md}");
        assert!(md.contains("walk-1 (0 only in a, 1 only in b)"), "{md}");

        // Distinct tolerance sets are listed once each, in first-seen order.
        let loose = CompareTolerances {
            position: 2.0,
            ..CompareTolerances::default()
        };
        let s3 = compare_traces("a", &a, "b", &b, &loose);
        let s1 = compare_traces("a", &a, "b", &b, &tol);
        let s2 = compare_traces("a", &a, "a", &a, &tol);
        let md = render_markdown(
            "t",
            &[
                ("1".into(), s1.clone()),
                ("3".into(), s3),
                ("2".into(), s2),
                ("1b".into(), s1),
            ],
        );
        let lines: Vec<&str> = md
            .lines()
            .filter(|l| l.starts_with("Tolerances:"))
            .collect();
        assert_eq!(lines.len(), 2, "{md}");
        assert!(lines[0].starts_with("Tolerances: position 1 uu"), "{md}");
        assert!(lines[1].starts_with("Tolerances: position 2 uu"), "{md}");
        // Fixed-rate comparisons with matching steps add nothing below the
        // table.
        assert!(!md.contains("Frame lengths differ"), "{md}");
        assert!(!md.contains("FOV did not count"), "{md}");
        assert!(!md.contains("noted about themselves"), "{md}");
    }

    /// Horizontal and vertical cells, rotator units, the mode, the FOV line
    /// and the replay's notes.
    #[test]
    fn components_mode_and_notes() {
        let a = trace(4, 0.0);
        let mut b = a.clone();
        b.samples[1].position += Vec3::new(3.0, 4.0, -1.0);
        b.samples[2].position.z += 0.5;
        b.samples[2].velocity = Vec3::new(0.0, 6.0, 8.0);
        b.samples[3].yaw = 2.0 * core::f32::consts::TAU / 65536.0;
        b.samples[3].fov = 50.0;
        let mut one = b.clone();
        one.meta.notes.push("one-step: resynchronised".to_owned());
        one.meta
            .notes
            .push("validity: tick 3 left out (teleport)".to_owned());
        let mut cached = a.clone();
        cached.meta.notes.push(format!(
            "{} on 4 of 4 samples",
            crate::convert::FOV_CACHED_NOTE_PREFIX
        ));
        let tol = CompareTolerances::default();
        let free = compare_traces("a", &a, "b", &b, &tol);
        let stepped = compare_traces("a", &cached, "b", &one, &tol);
        let mut old = free.clone();
        old.components = None;
        old.fov = None;
        let md = render_markdown(
            "t",
            &[
                ("free".into(), free),
                ("stepped".into(), stepped),
                ("old".into(), old),
            ],
        );
        let row = |name: &str| {
            md.lines()
                .find(|l| l.starts_with(&format!("| {name} |")))
                .unwrap_or_else(|| panic!("no row {name}:\n{md}"))
                .to_owned()
        };
        let rms = |sum_sq: f64| (sum_sq / 4.0_f64).sqrt();
        assert!(
            row("free").contains(&format!(
                "| free | 4 | 5.000 / {:.3} | 1.000 / {:.3} (-1.000 .. +0.500) | 6.000 / {:.3} | \
                 8.000 / {:.3} (+0.000 .. +8.000) | 0.0110° / 2.0 | 0.0000° / 0.0 |",
                rms(25.0),
                rms(1.25),
                rms(36.0),
                rms(64.0)
            )),
            "{md}"
        );
        assert!(row("stepped").contains("| one-step | 4 | 5.000 / "), "{md}");
        assert!(
            row("old").contains("| free | 4 | 3-D: 5.099 / ")
                && row("old").contains(" | ? | 3-D: "),
            "{md}"
        );
        // The FOV decides the free comparison's first divergence only when
        // it counts; position comes first here in both.
        assert!(row("free").contains("tick 1 (position, 5.0990)"), "{md}");
        assert!(
            md.contains(
                "The FOV did not count for the verdict of: stepped (the notes of trace a say \
                 that its FOV column is the camera's cached view FOV, which does not show the \
                 zoom; FOV max 40.000°)."
            ),
            "{md}"
        );
        assert!(
            md.contains(
                "What the replays noted about themselves:\n\n- stepped: one-step: \
                 resynchronised\n- stepped: validity: tick 3 left out (teleport)\n"
            ),
            "{md}"
        );
        let cells = |l: &str| l.matches(" | ").count();
        let header = md.lines().find(|l| l.starts_with("| Comparison")).unwrap();
        for name in ["free", "stepped", "old"] {
            assert_eq!(cells(&row(name)), cells(header), "{name}\n{md}");
        }
    }

    /// `trace(n, 1.0)` with real sample times: fixed 60 Hz, or the given
    /// frame lengths and no fixed rate.
    fn timed(n: u64, lengths: Option<&dyn Fn(u64) -> f64>) -> Trace {
        let mut t = trace(n, 1.0);
        let mut time = 0.0;
        for s in &mut t.samples {
            if s.tick > 0 {
                time += lengths.map_or(1.0 / 60.0, |f| f(s.tick));
            }
            s.time = time;
        }
        if lengths.is_some() {
            t.meta.tick_rate = None;
        }
        t
    }

    #[test]
    fn time_step_column() {
        let tol = CompareTolerances::default();
        let fixed = timed(40, None);
        let uneven = |k: u64| 0.014 + 0.001 * (k % 5) as f64;
        let var = timed(40, Some(&uneven));
        let same = compare_traces("a", &fixed, "b", &fixed, &tol);
        let per_sample = compare_traces("a", &var, "b", &var, &tol);
        let misstepped = compare_traces("a", &var, "b", &fixed, &tol);
        let mut forced = var.clone();
        forced.meta.tick_rate = Some(60.0);
        let labels = compare_traces("a", &var, "b", &forced, &tol);
        let mut old = same.clone();
        old.timing = None;
        let md = render_markdown(
            "t",
            &[
                ("fixed".into(), same),
                ("variable".into(), per_sample),
                ("wrong-step".into(), misstepped),
                ("labels".into(), labels),
                ("old".into(), old),
            ],
        );
        let row = |name: &str| {
            md.lines()
                .find(|l| l.starts_with(&format!("| {name} |")))
                .unwrap_or_else(|| panic!("no row {name}:\n{md}"))
                .to_owned()
        };
        assert!(md.contains("| Verdict | Time step |"), "{md}");
        assert!(row("fixed").ends_with("| exact | 60 Hz |"), "{md}");
        assert!(
            row("variable")
                .ends_with("| exact | variable 0.014000..0.018000 s (mean 0.016051 s) |"),
            "{md}"
        );
        assert!(
            row("wrong-step").ends_with(
                "| exact | **differs**: a variable 0.014000..0.018000 s (mean 0.016051 s), b 60 Hz |"
            ),
            "{md}"
        );
        // Same lengths under different labels: both are named.
        assert!(
            row("labels")
                .ends_with("| a variable 0.014000..0.018000 s (mean 0.016051 s), b 60 Hz |"),
            "{md}"
        );
        assert!(!row("labels").contains("differs"), "{md}");
        assert!(row("old").ends_with("| exact | ? |"), "{md}");
        let notes: Vec<&str> = md
            .lines()
            .filter(|l| l.starts_with("Frame lengths differ"))
            .collect();
        assert_eq!(notes.len(), 1, "{md}");
        assert!(
            notes[0].contains(
                "wrong-step (39 of 39 ticks, first at tick 1; elapsed time differs by up to 0.0"
            ),
            "{md}"
        );
        assert!(!notes[0].contains("labels") && !notes[0].contains("variable ("));
        // Every table row has the same number of cells as the header.
        let cells = |l: &str| l.matches(" | ").count();
        let header = md.lines().find(|l| l.starts_with("| Comparison")).unwrap();
        for name in ["fixed", "variable", "wrong-step", "labels", "old"] {
            assert_eq!(cells(&row(name)), cells(header), "{name}\n{md}");
        }
    }
}
