//! Synthetic UE3 v868 package writer for tests.
//!
//! Written independently of the library's own summary serializer so that the
//! reader is validated against a second implementation of the layout. Every
//! fixture is generated byte by byte here; no original game data is involved.

#![allow(dead_code, clippy::unwrap_used)]

pub const TAG: u32 = 0x9E2A_83C1;

/// Little-endian byte sink.
#[derive(Default)]
pub struct W(pub Vec<u8>);

impl W {
    pub fn u16(&mut self, v: u16) {
        self.0.extend_from_slice(&v.to_le_bytes());
    }
    pub fn u32(&mut self, v: u32) {
        self.0.extend_from_slice(&v.to_le_bytes());
    }
    pub fn i32(&mut self, v: i32) {
        self.0.extend_from_slice(&v.to_le_bytes());
    }
    pub fn u64(&mut self, v: u64) {
        self.0.extend_from_slice(&v.to_le_bytes());
    }
    pub fn bytes(&mut self, b: &[u8]) {
        self.0.extend_from_slice(b);
    }
    /// Latin-1 FString (ASCII in tests) with NUL.
    pub fn fstring(&mut self, s: &str) {
        if s.is_empty() {
            self.i32(0);
            return;
        }
        self.i32(s.len() as i32 + 1);
        self.bytes(s.as_bytes());
        self.0.push(0);
    }
    pub fn len(&self) -> usize {
        self.0.len()
    }
}

#[derive(Clone, Debug)]
pub struct Import {
    pub class_package: i32,
    pub class_name: i32,
    pub outer: i32,
    pub name: i32,
    pub number: i32,
}

#[derive(Clone, Debug)]
pub struct Export {
    pub class: i32,
    pub super_: i32,
    pub outer: i32,
    pub name: i32,
    pub number: i32,
    pub archetype: i32,
    pub object_flags: u64,
    pub payload: Vec<u8>,
    pub export_flags: u32,
    pub net_counts: Vec<i32>,
    pub guid: [u32; 4],
    pub package_flags: u32,
}

/// Editor thumbnail: table entry plus record.
#[derive(Clone, Debug)]
pub struct Thumb {
    pub class: String,
    pub path: String,
    pub width: i32,
    pub height: i32,
    pub data: Vec<u8>,
}

#[derive(Clone, Debug)]
pub struct TexAlloc {
    pub size_x: i32,
    pub size_y: i32,
    pub num_mips: i32,
    pub format: u32,
    pub flags: u32,
    pub export_indices: Vec<i32>,
}

/// Description of a synthetic package.
#[derive(Clone, Debug)]
pub struct Synth {
    pub package_flags: u32,
    pub names: Vec<(String, u64)>,
    pub imports: Vec<Import>,
    pub exports: Vec<Export>,
    pub additional_packages: Vec<String>,
    pub texture_allocations: Vec<TexAlloc>,
    pub guid: [u32; 4],
    pub package_source: u32,
    pub engine_version: i32,
    pub cooker_version: i32,
    /// Emit a depends map (one empty TArray per export).
    pub depends: bool,
    /// Thumbnail records + table after the depends map (none = offset 0).
    pub thumbnails: Vec<Thumb>,
}

/// Offsets computed while laying out the uncompressed stream.
#[derive(Clone, Debug, Default)]
pub struct Layout {
    pub summary_len: usize,
    pub name_offset: usize,
    pub import_offset: usize,
    pub export_offset: usize,
    pub depends_offset: usize,
    /// End of the depends map (= ImportExportGuidsOffset).
    pub ieguids_offset: usize,
    /// Thumbnail record offsets.
    pub thumb_offsets: Vec<usize>,
    /// Thumbnail table offset (0 = none).
    pub thumb_table_offset: usize,
    pub header_end: usize,
    pub payload_offsets: Vec<usize>,
}

pub const NAMES: &[&str] = &[
    "None",        // 0
    "Core",        // 1
    "Package",     // 2
    "Class",       // 3
    "Engine",      // 4
    "PlayerStart", // 5
    "TestPkg",     // 6
    "TestActor",   // 7
    "Actor",       // 8
    "TheWorld",    // 9
    "World",       // 10
    "Obj",         // 11
];

impl Synth {
    /// A tiny but complete package:
    /// imports: Core (Package), Engine (Package), Engine.PlayerStart (Class), Engine.World (Class),
    ///          Core.Package (Class)
    /// exports: TestPkg (Package), TestPkg.TestActor (Class, super Engine.PlayerStart),
    ///          TheWorld (World), TheWorld.Obj_2 (PlayerStart), TheWorld.Obj (TestActor)
    pub fn sample() -> Synth {
        let names = NAMES
            .iter()
            .enumerate()
            .map(|(i, n)| (n.to_string(), 0x0007_0010_0000_0000u64 + i as u64))
            .collect();
        let imp = |cp, cn, outer, name| Import {
            class_package: cp,
            class_name: cn,
            outer,
            name,
            number: 0,
        };
        let imports = vec![
            imp(1, 2, 0, 1),   // -1 Core
            imp(1, 2, 0, 4),   // -2 Engine
            imp(1, 3, -2, 5),  // -3 Engine.PlayerStart
            imp(1, 3, -2, 10), // -4 Engine.World
            imp(1, 3, -1, 2),  // -5 Core.Package
        ];
        let exp = |class, super_, outer, name, number, payload: &[u8]| Export {
            class,
            super_,
            outer,
            name,
            number,
            archetype: 0,
            object_flags: 0x0007_0004_0000_0000,
            payload: payload.to_vec(),
            export_flags: 1,
            net_counts: Vec::new(),
            guid: [0; 4],
            package_flags: 0,
        };
        let mut pkg_export = exp(-5, 0, 0, 6, 0, &[0u8; 12]);
        pkg_export.net_counts = vec![2];
        pkg_export.guid = [0x1111_1111, 0x2222_2222, 0x3333_3333, 0x4444_4444];
        pkg_export.package_flags = 0x0020_0000;
        let exports = vec![
            pkg_export,                                   // 1 TestPkg
            exp(0, -3, 1, 7, 0, b"class-payload-bytes"),  // 2 TestPkg.TestActor
            exp(-4, 0, 0, 9, 0, &[7u8; 33]),              // 3 TheWorld
            exp(-3, 0, 3, 11, 3, &[1, 2, 3, 4, 5, 6, 7]), // 4 TheWorld.Obj_2
            exp(2, 0, 3, 11, 0, &[9u8; 300]),             // 5 TheWorld.Obj
        ];
        Synth {
            package_flags: 0x0002_0008,
            names,
            imports,
            exports,
            additional_packages: vec!["sublevel_a".into()],
            texture_allocations: vec![TexAlloc {
                size_x: 256,
                size_y: 128,
                num_mips: 9,
                format: 3,
                flags: 0x10,
                export_indices: vec![4, 5],
            }],
            guid: [0xDEAD_BEEF, 1, 2, 3],
            package_source: 0x1234_5678,
            engine_version: 12097,
            cooker_version: 136,
            depends: true,
            thumbnails: Vec::new(),
        }
    }

    /// [`Synth::sample`] plus two thumbnails: one with (fake, test-written)
    /// image bytes and one empty `0 x 0` record, as seen in shipped packages.
    pub fn with_thumbnails() -> Synth {
        let mut s = Synth::sample();
        let mut image = b"\x89PNG\r\n\x1a\n".to_vec();
        image.extend((0..40u8).map(|i| i.wrapping_mul(7)));
        s.thumbnails = vec![
            Thumb {
                class: "Texture2D".into(),
                path: "TestPkg.TestActor".into(),
                width: 64,
                height: 32,
                data: image,
            },
            Thumb {
                class: "World".into(),
                path: "TheWorld".into(),
                width: 0,
                height: 0,
                data: Vec::new(),
            },
        ];
        s
    }

    fn write_summary(&self, w: &mut W, l: &Layout, compression: u32, chunks: &[[i32; 4]]) {
        w.u32(TAG);
        w.u16(868);
        w.u16(0);
        w.i32(l.header_end as i32);
        w.fstring("None");
        w.u32(self.package_flags);
        w.i32(self.names.len() as i32);
        w.i32(l.name_offset as i32);
        w.i32(self.exports.len() as i32);
        w.i32(l.export_offset as i32);
        w.i32(self.imports.len() as i32);
        w.i32(l.import_offset as i32);
        w.i32(l.depends_offset as i32);
        w.i32(l.ieguids_offset as i32); // ImportExportGuidsOffset
        w.i32(0);
        w.i32(0);
        w.i32(l.thumb_table_offset as i32);
        for g in self.guid {
            w.u32(g);
        }
        w.i32(1);
        w.i32(self.exports.len() as i32);
        w.i32(self.names.len() as i32);
        w.i32(self.exports.len() as i32);
        w.i32(self.engine_version);
        w.i32(self.cooker_version);
        w.u32(compression);
        w.i32(chunks.len() as i32);
        for c in chunks {
            for v in c {
                w.i32(*v);
            }
        }
        w.u32(self.package_source);
        w.i32(self.additional_packages.len() as i32);
        for s in &self.additional_packages {
            w.fstring(s);
        }
        w.i32(self.texture_allocations.len() as i32);
        for t in &self.texture_allocations {
            w.i32(t.size_x);
            w.i32(t.size_y);
            w.i32(t.num_mips);
            w.u32(t.format);
            w.u32(t.flags);
            w.i32(t.export_indices.len() as i32);
            for i in &t.export_indices {
                w.i32(*i);
            }
        }
    }

    /// Body (everything after the summary) for a given layout.
    fn write_body(&self, l: &Layout) -> Vec<u8> {
        let mut w = W::default();
        for (n, f) in &self.names {
            w.fstring(n);
            w.u64(*f);
        }
        assert_eq!(l.summary_len + w.len(), l.import_offset);
        for i in &self.imports {
            w.i32(i.class_package);
            w.i32(0);
            w.i32(i.class_name);
            w.i32(0);
            w.i32(i.outer);
            w.i32(i.name);
            w.i32(i.number);
        }
        assert_eq!(l.summary_len + w.len(), l.export_offset);
        for (k, e) in self.exports.iter().enumerate() {
            w.i32(e.class);
            w.i32(e.super_);
            w.i32(e.outer);
            w.i32(e.name);
            w.i32(e.number);
            w.i32(e.archetype);
            w.u64(e.object_flags);
            w.i32(e.payload.len() as i32);
            w.i32(l.payload_offsets[k] as i32);
            w.u32(e.export_flags);
            w.i32(e.net_counts.len() as i32);
            for c in &e.net_counts {
                w.i32(*c);
            }
            for g in e.guid {
                w.u32(g);
            }
            w.u32(e.package_flags);
        }
        if self.depends {
            assert_eq!(l.summary_len + w.len(), l.depends_offset);
            for _ in &self.exports {
                w.i32(0);
            }
        }
        assert_eq!(l.summary_len + w.len(), l.ieguids_offset);
        for (t, &off) in self.thumbnails.iter().zip(&l.thumb_offsets) {
            assert_eq!(l.summary_len + w.len(), off);
            w.i32(t.width);
            w.i32(t.height);
            w.i32(t.data.len() as i32);
            w.bytes(&t.data);
        }
        if !self.thumbnails.is_empty() {
            assert_eq!(l.summary_len + w.len(), l.thumb_table_offset);
            w.i32(self.thumbnails.len() as i32);
            for (t, &off) in self.thumbnails.iter().zip(&l.thumb_offsets) {
                w.fstring(&t.class);
                w.fstring(&t.path);
                w.i32(off as i32);
            }
        }
        assert_eq!(l.summary_len + w.len(), l.header_end);
        for e in &self.exports {
            w.bytes(&e.payload);
        }
        w.0
    }

    fn layout(&self, summary_len: usize) -> Layout {
        let names_len: usize = self
            .names
            .iter()
            .map(|(n, _)| 4 + if n.is_empty() { 0 } else { n.len() + 1 } + 8)
            .sum();
        let imports_len = self.imports.len() * 28;
        let exports_len: usize = self
            .exports
            .iter()
            .map(|e| 68 + 4 * e.net_counts.len())
            .sum();
        let depends_len = if self.depends {
            4 * self.exports.len()
        } else {
            0
        };
        let fstr_len = |s: &str| 4 + if s.is_empty() { 0 } else { s.len() + 1 };
        let name_offset = summary_len;
        let import_offset = name_offset + names_len;
        let export_offset = import_offset + imports_len;
        let depends_offset = export_offset + exports_len;
        let ieguids_offset = depends_offset + depends_len;
        let mut thumb_offsets = Vec::new();
        let mut q = ieguids_offset;
        for t in &self.thumbnails {
            thumb_offsets.push(q);
            q += 12 + t.data.len();
        }
        let (thumb_table_offset, header_end) = if self.thumbnails.is_empty() {
            (0, ieguids_offset)
        } else {
            let table_len: usize = 4 + self
                .thumbnails
                .iter()
                .map(|t| fstr_len(&t.class) + fstr_len(&t.path) + 4)
                .sum::<usize>();
            (q, q + table_len)
        };
        let mut payload_offsets = Vec::new();
        let mut p = header_end;
        for e in &self.exports {
            payload_offsets.push(p);
            p += e.payload.len();
        }
        Layout {
            summary_len,
            name_offset,
            import_offset,
            export_offset,
            depends_offset: if self.depends { depends_offset } else { 0 },
            ieguids_offset,
            thumb_offsets,
            thumb_table_offset,
            header_end,
            payload_offsets,
        }
    }

    /// Uncompressed package file (== its own stream) and its layout.
    pub fn build(&self) -> (Vec<u8>, Layout) {
        let mut probe = W::default();
        self.write_summary(&mut probe, &Layout::default(), 0, &[]);
        let l = self.layout(probe.len());
        let mut w = W::default();
        self.write_summary(&mut w, &l, 0, &[]);
        assert_eq!(w.len(), l.summary_len);
        w.bytes(&self.write_body(&l));
        (w.0, l)
    }

    /// LZO-compressed package file plus the expected uncompressed stream.
    /// The body is split into chunks of `chunk_size` bytes, each into blocks of
    /// `block_size` bytes, every block encoded as an LZO1X literal-only stream.
    pub fn build_compressed(&self, chunk_size: usize, block_size: usize) -> (Vec<u8>, Vec<u8>) {
        let (stream, l) = self.build();
        let body = &stream[l.summary_len..];
        let pieces: Vec<&[u8]> = body.chunks(chunk_size).collect();
        let n = pieces.len();
        let comp_summary_len = l.summary_len + 16 * n;
        let mut chunk_bytes = Vec::new();
        let mut table = Vec::new();
        let mut file_pos = comp_summary_len;
        let mut u_pos = l.summary_len;
        for piece in &pieces {
            let blocks: Vec<&[u8]> = piece.chunks(block_size).collect();
            let encoded: Vec<Vec<u8>> = blocks.iter().map(|b| lzo_literal(b)).collect();
            let csum: usize = encoded.iter().map(Vec::len).sum();
            let mut c = W::default();
            c.u32(TAG);
            c.i32(block_size as i32);
            c.i32(csum as i32);
            c.i32(piece.len() as i32);
            for (b, e) in blocks.iter().zip(&encoded) {
                c.i32(e.len() as i32);
                c.i32(b.len() as i32);
            }
            for e in &encoded {
                c.bytes(e);
            }
            table.push([
                u_pos as i32,
                piece.len() as i32,
                file_pos as i32,
                c.len() as i32,
            ]);
            file_pos += c.len();
            u_pos += piece.len();
            chunk_bytes.push(c.0);
        }
        let mut w = W::default();
        self.write_summary(&mut w, &l, 2, &table);
        assert_eq!(w.len(), comp_summary_len);
        for c in chunk_bytes {
            w.bytes(&c);
        }
        (w.0, stream)
    }
}

/// Encode `data` as a single-literal-run LZO1X stream followed by the end
/// marker (`0x11 0x00 0x00`).
pub fn lzo_literal(data: &[u8]) -> Vec<u8> {
    let n = data.len();
    let mut out = Vec::with_capacity(n + 8);
    if n == 0 {
        // nothing but the end marker
    } else if n <= 238 {
        out.push((17 + n) as u8);
    } else {
        // General literal run: 0, k zero bytes, b; length = 18 + 255k + b.
        let rest = n - 18;
        let k = (rest - 1) / 255;
        let b = rest - 255 * k;
        out.push(0);
        out.extend(std::iter::repeat_n(0u8, k));
        out.push(b as u8);
    }
    out.extend_from_slice(data);
    out.extend_from_slice(&[0x11, 0, 0]);
    out
}

/// Offset of the `NameCount` field in a summary with FolderName "None".
pub const OFF_NAME_COUNT: usize = 0x19;
pub const OFF_NAME_OFFSET: usize = 0x1D;
pub const OFF_EXPORT_COUNT: usize = 0x21;
pub const OFF_EXPORT_OFFSET: usize = 0x25;
pub const OFF_IMPORT_COUNT: usize = 0x29;
pub const OFF_IMPORT_OFFSET: usize = 0x2D;
pub const OFF_TOTAL_HEADER_SIZE: usize = 0x08;
pub const OFF_DEPENDS_OFFSET: usize = 0x31;
pub const OFF_IEGUIDS_OFFSET: usize = 0x35;
pub const OFF_IMPORT_GUIDS_COUNT: usize = 0x39;
pub const OFF_EXPORT_GUIDS_COUNT: usize = 0x3D;
pub const OFF_THUMBNAIL_TABLE_OFFSET: usize = 0x41;
pub const OFF_GENERATION_COUNT: usize = 0x55;
/// With one generation entry.
pub const OFF_COMPRESSION_FLAGS: usize = 0x6D;
pub const OFF_CHUNK_COUNT: usize = 0x71;
pub const OFF_FIRST_CHUNK: usize = 0x75;

pub fn put_i32(buf: &mut [u8], off: usize, v: i32) {
    buf[off..off + 4].copy_from_slice(&v.to_le_bytes());
}

pub fn get_i32(buf: &[u8], off: usize) -> i32 {
    i32::from_le_bytes(buf[off..off + 4].try_into().unwrap())
}

/// Call every accessor on a parsed package; must never panic.
pub fn exercise(p: &asamu_ue3::Package) {
    use asamu_ue3::PackageIndex;
    let _ = p.class_census();
    for i in 0..p.exports.len() {
        let _ = p.export_path(i);
        let _ = p.export_class_name(i);
        let _ = p.export_class_package(i);
        let _ = p.export_data(i);
        let e = &p.exports[i];
        for idx in [
            e.class_index,
            e.super_index,
            e.outer_index,
            e.archetype_index,
        ] {
            let _ = p.object_path(idx);
            let _ = p.class_name(idx);
            let _ = p.root_name(idx);
        }
    }
    for i in 0..p.imports.len() {
        let _ = p.import_path(i);
        let _ = p.root_name(PackageIndex::from_import(i).unwrap());
    }
    for v in [0, 1, -1, i32::MAX, i32::MIN, 1000, -1000] {
        let _ = p.object_path(PackageIndex(v));
        let _ = p.resolve(PackageIndex(v));
    }
    let _ = p.top_level_exports().count();
    let _ = p.export_data(usize::MAX);
    let _ = p.export_path(usize::MAX);
    let _ = p.import_path(usize::MAX);
    let _ = p.export_class_package(usize::MAX);
    let _ = p.find_exports("Obj");
    for n in p.names.iter().take(4) {
        let _ = p.find_exports(&n.name);
    }
    for i in [0, -1, i32::MAX, i32::MIN] {
        let _ = p.name(i);
        let _ = p.try_fname(asamu_ue3::FName {
            index: i,
            number: i,
        });
    }
    if let Some(t) = &p.thumbnails {
        let _ = t.iter().map(|e| e.end).max();
    }
    let _ = p.has_errors();
    let _ = p.summary.to_uncompressed_bytes();
}
